targets:
  main:
    resources:
      RawSerialPort:
        port: "/dev/ttyUSB0"
        speed: 1500000
    drivers:
      ManualPowerDriver:
        name: "example"
      SerialDriver: {}
      UBootDriver:
        prompt: '=>'
